import json

examples = [
    # Security (30)
    ("CVE-2023-1234 details", "security"), ("latest apache vulnerability", "security"),
    ("log4shell exploit check", "security"), ("windows zero day advisory", "security"),
    ("nvd score for CVE-2021-44228", "security"), ("cisa known exploited vulnerabilities", "security"),
    ("github advisory GHSA-abc", "security"), ("mitre att&ck framework", "security"),
    ("ubuntu security patch tracker", "security"), ("debian security advisory 123", "security"),
    ("redhat cve database", "security"), ("suse security updates", "security"),
    ("npm audit high vulnerability", "security"), ("is ssh vulnerable to terrapin", "security"),
    ("openssl security advisory 2024", "security"), ("linux kernel privilege escalation cve", "security"),
    ("spring boot remote code execution", "security"), ("jackson databind cve", "security"),
    ("chrome zero day update", "security"), ("ios 17 security content", "security"),
    ("android security bulletin", "security"), ("vmware esxi vulnerability", "security"),
    ("citrix netscaler cve", "security"), ("fortinet vpn exploit", "security"),
    ("palo alto pan-os advisory", "security"), ("cisco ios xe vulnerability", "security"),
    ("f5 big-ip security advisory", "security"), ("atlassian confluence cve", "security"),
    ("gitlab security release", "security"), ("jenkins security advisory", "security"),

    # Vendor-Status (30)
    ("github status", "vendor-status"), ("aws health dashboard", "vendor-status"),
    ("cloudflare outage today", "vendor-status"), ("slack connection issues", "vendor-status"),
    ("npm registry down", "vendor-status"), ("vercel deployment status", "vendor-status"),
    ("discord server outage", "vendor-status"), ("openai chatgpt down", "vendor-status"),
    ("azure devops status", "vendor-status"), ("datadog status page", "vendor-status"),
    ("pagerduty incident response", "vendor-status"), ("gcp status dashboard", "vendor-status"),
    ("heroku platform status", "vendor-status"), ("netlify status", "vendor-status"),
    ("digitalocean status", "vendor-status"), ("linode system status", "vendor-status"),
    ("stripe api status", "vendor-status"), ("twilio status page", "vendor-status"),
    ("sendgrid incident", "vendor-status"), ("mailgun status", "vendor-status"),
    ("zoom outage", "vendor-status"), ("teams connection issues", "vendor-status"),
    ("notion status", "vendor-status"), ("figma outage", "vendor-status"),
    ("miro status", "vendor-status"), ("asana performance degradation", "vendor-status"),
    ("jira cloud status", "vendor-status"), ("confluence down", "vendor-status"),
    ("bitbucket status", "vendor-status"), ("gitlab.com status", "vendor-status"),

    # Papers (30)
    ("arxiv machine learning papers", "papers"), ("attention is all you need pdf", "papers"),
    ("transformer models research paper", "papers"), ("deep learning semantic scholar", "papers"),
    ("doi 10.1038/s41586-020-2649-2", "papers"), ("nature medicine latest articles", "papers"),
    ("science journal quantum supremacy", "papers"), ("pubmed covid vaccine efficacy", "papers"),
    ("ieee transactions on pattern analysis", "papers"), ("acm digital library search", "papers"),
    ("researchgate download pdf", "papers"), ("google scholar citation count", "papers"),
    ("llama 2 open foundation and fine-tuned chat models", "papers"),
    ("gpt-4 technical report arxiv", "papers"), ("instructgpt paper", "papers"),
    ("lora low-rank adaptation paper", "papers"), ("flashattention algorithm paper", "papers"),
    ("direct preference optimization paper", "papers"), ("mixture of experts research", "papers"),
    ("contrastive language-image pretraining paper", "papers"), ("clip model openai paper", "papers"),
    ("diffusion models beat gans paper", "papers"), ("stable diffusion latent paper", "papers"),
    ("nerf neural radiance fields paper", "papers"), ("yolo object detection paper", "papers"),
    ("resnet deep residual learning paper", "papers"), ("alexnet imagenet paper", "papers"),
    ("word2vec mikolov paper", "papers"), ("bert pre-training of deep bidirectional transformers", "papers"),
    ("roberta robustly optimized bert pretraining approach", "papers"),

    # Specs (30)
    ("rfc 793 tcp specification", "specs"), ("http/2 rfc 7540", "specs"),
    ("websocket protocol rfc 6455", "specs"), ("tls 1.3 rfc 8446", "specs"),
    ("jwt json web token rfc 7519", "specs"), ("oauth 2.0 authorization framework rfc 6749", "specs"),
    ("openid connect core 1.0", "specs"), ("saml 2.0 specification", "specs"),
    ("html living standard whatwg", "specs"), ("dom specification w3c", "specs"),
    ("css flexbox level 1", "specs"), ("ecmascript language specification ecma-262", "specs"),
    ("webassembly core specification", "specs"), ("openapi specification 3.0.3", "specs"),
    ("asyncapi specification", "specs"), ("graphql specification october 2021", "specs"),
    ("json schema specification", "specs"), ("xml 1.0 specification", "specs"),
    ("xpath 3.1 w3c recommendation", "specs"), ("xslt 3.0 specification", "specs"),
    ("svg 2 w3c candidate recommendation", "specs"), ("webrtc w3c specification", "specs"),
    ("webgl specification", "specs"), ("opengl 4.6 core profile", "specs"),
    ("vulkan 1.3 specification", "specs"), ("posix.1-2017 standard", "specs"),
    ("c11 iso/iec 9899:2011", "specs"), ("c++20 iso/iec 14882:2020", "specs"),
    ("ieee 754 floating-point standard", "specs"), ("unicode 15.0.0 core specification", "specs"),

    # Package-Registry (30)
    ("npm express package", "package-registry"), ("yarn add react-dom", "package-registry"),
    ("pnpm install typescript", "package-registry"), ("pypi numpy release", "package-registry"),
    ("pip install pandas", "package-registry"), ("cargo publish crate", "package-registry"),
    ("crates.io tokio", "package-registry"), ("maven central repository search", "package-registry"),
    ("gradle dependencies spring-boot", "package-registry"), ("gem install bundler", "package-registry"),
    ("rubygems rails version", "package-registry"), ("composer require symfony/console", "package-registry"),
    ("packagist laravel/framework", "package-registry"), ("nuget package manager newtonsoft.json", "package-registry"),
    ("dotnet add package", "package-registry"), ("go get golang.org/x/crypto", "package-registry"),
    ("pkg.go.dev net/http", "package-registry"), ("cran install.packages('dplyr')", "package-registry"),
    ("docker hub nginx official image", "package-registry"), ("ghcr.io github container registry", "package-registry"),
    ("homebrew install wget", "package-registry"), ("apt-get install curl", "package-registry"),
    ("yum install httpd", "package-registry"), ("apk add alpine-sdk", "package-registry"),
    ("pacman -S archlinux-keyring", "package-registry"), ("choco install git", "package-registry"),
    ("winget install powertoys", "package-registry"), ("vcpkg install boost", "package-registry"),
    ("conan install fmt", "package-registry"), ("nix-env -iA nixpkgs.hello", "package-registry"),

    # Github (30)
    ("github.com/torvalds/linux", "github"), ("microsoft/vscode github repo", "github"),
    ("pull request #42 on facebook/react", "github"), ("issue #100 in vercel/next.js", "github"),
    ("github discussions tailwindlabs/tailwindcss", "github"), ("github releases kubernetes/kubernetes", "github"),
    ("github api get user", "github"), ("github actions workflow syntax", "github"),
    ("github pages deployment", "github"), ("github copilot documentation", "github"),
    ("github codespaces setup", "github"), ("github advanced security features", "github"),
    ("github enterprise server admin guide", "github"), ("github webhooks documentation", "github"),
    ("github apps authentication", "github"), ("github oauth login flow", "github"),
    ("github graphql api explorer", "github"), ("github rest api reference", "github"),
    ("github cli gh pr create", "github"), ("github desktop release notes", "github"),
    ("github student developer pack", "github"), ("github sponsors program", "github"),
    ("github trending repositories", "github"), ("github search issues and pull requests", "github"),
    ("github markdown syntax guide", "github"), ("github wiki pages", "github"),
    ("github project boards", "github"), ("github milestones and labels", "github"),
    ("github branch protection rules", "github"), ("github codeowners file", "github"),

    # Changelog (30)
    ("react 18 changelog", "changelog"), ("python 3.11 release notes", "changelog"),
    ("node.js v20 release history", "changelog"), ("typescript 5.0 what's new", "changelog"),
    ("next.js 13 changelog", "changelog"), ("vue 3 release notes", "changelog"),
    ("angular v16 update guide", "changelog"), ("svelte 4 announcement", "changelog"),
    ("tailwind css v3.3 changelog", "changelog"), ("bootstrap 5 migration guide", "changelog"),
    ("docker desktop 4.20 release notes", "changelog"), ("kubernetes 1.28 changelog", "changelog"),
    ("ubuntu 22.04 lts release notes", "changelog"), ("mac os sonoma features", "changelog"),
    ("ios 17 release notes", "changelog"), ("android 14 new features", "changelog"),
    ("windows 11 update history", "changelog"), ("chrome browser release notes", "changelog"),
    ("firefox latest version changelog", "changelog"), ("safari 17 features", "changelog"),
    ("vscode march 2023 update", "changelog"), ("intellij idea 2023.2 what's new", "changelog"),
    ("visual studio 2022 release notes", "changelog"), ("xcode 15 beta release notes", "changelog"),
    ("rust 1.70 release announcement", "changelog"), ("go 1.21 release notes", "changelog"),
    ("java 21 new features", "changelog"), ("c# 12 language changes", "changelog"),
    ("php 8.2 changelog", "changelog"), ("ruby 3.2 release", "changelog"),

    # Forums (30)
    ("stackoverflow how to center a div", "forums"), ("reddit r/learnprogramming", "forums"),
    ("stackexchange unix and linux", "forums"), ("serverfault nginx configuration", "forums"),
    ("superuser windows 11 taskbar", "forums"), ("mathoverflow topology question", "forums"),
    ("hacker news ycombinator front page", "forums"), ("lobsters computing discussion", "forums"),
    ("dev.to web development articles", "forums"), ("hashnode blogging platform for developers", "forums"),
    ("medium programming tutorials", "forums"), ("quora what is the best programming language", "forums"),
    ("discourse forum hosting", "forums"), ("rust users forum", "forums"),
    ("python discuss forum", "forums"), ("go forum golangbridge", "forums"),
    ("swift forums apple", "forums"), ("kotlin discussions", "forums"),
    ("reactiflux discord community", "forums"), ("vue land discord", "forums"),
    ("kubernetes slack channel", "forums"), ("cncf slack community", "forums"),
    ("elixir forum", "forums"), ("crystal lang forum", "forums"),
    ("zig showtime discord", "forums"), ("nim forum", "forums"),
    ("julialang discourse", "forums"), ("rstudio community", "forums"),
    ("unity forums", "forums"), ("unreal engine forums", "forums"),
]

with open("data/router/synthetic-train.jsonl", "w") as f:
    for query, label in examples:
        d = {
            "query": query,
            "label": label,
            "rationale": f"Synthetic training example for {label}",
            "inputText": query
        }
        f.write(json.dumps(d) + "\n")

print(f"Generated {len(examples)} synthetic training examples.")
